console.log('process.arch:', process.arch)
console.log('process.platform:', process.platform)
console.log('process.version:', process.version)
console.log('process.uptime():', process.uptime())
console.log('process.env:', process.env)
